### PR TITLE
chore: added missing german stations

### PR DESCRIPTION
**Pull request by SiddharthKhatsuriya**
Added missing German weather station from DWD database.

Note: when comparing the DWD databse and meteostat there were 520+ stations missing, but accordign to the `find_duplicates` logic ~180 of these missing stations are not getting added because they are probably too close to each other. I have added `scripts\germany\duplicate_stations_reported.json` which shows all the stations that are considered duplicate.

### CODE REVIEW

**Comment by peterhaufler** [comment]
@clampr I found this pull request after realizing, that DWD stations are missing in the Meteostat system. Has this pull request been denied or only been forgotten? What would it take to merge this pull request and close the DWD station gap in the Meteostat system?

**Comment by clampr** [comment]
First, I want to appologize for taking so much time to review this PR. Great job @SiddharthKhatsuriya 🙂 

I added the ISO codes for the regions (Bundesländer) and the time zone. Also fixed the pipeline errors.

@peterhaufler could you be so kind and review the changes? I'd like to know if it roughly matches the discrepancy that you guys have identified. Obviously, we're still missing the stations that have been flagged as duplicates. Will create a follow-up issue for these stations.

**Comment by peterhaufler** [comment]
@clampr thanks for taking care for this pull request :) On my side, I just realised, that for one of our weather insurance contracts, there was a much nearer weather station available "Bochum" to the insured location, than the one provided by Meteostat. I found that station in this pull request (id LH10Y).
So I am sure that this will be a good improvement, but I did no systematic check, if there are still stations missing.
But of cause if there are still stations flagged as duplicates, that are not duplicates and will not be added with this pull request, we are very interested on a follow up so at the end all German stations are in the system.

**Comment by clampr** [comment]
Follow-up issue created (#489).

**Comment by ShishirRmc** [comment]
I might be a little too late but is the duplicate station situation still persists? Its funny I didn't see Its closed and went straight to the problem. I did find out that Burgbernheim (ID: 00801) is a duplicate of Illesheim (ID: 10752). They are the closure cities and one serves them both(I guess). and i thinkI might be the clown here but reply would be appreciated.

**Pull request merged**
